#!/bin/bash

WIFS= read -r -d '' MY_ART << 'EOF'
  _________.__           .__  .__         .__              
 /   _____/|  |__   ____ |  | |  |   ____ |__| ____  ____  
 \_____  \ |  |  \_/ __ \|  | |  |  /    \|  | ____\/ __ \ 
 /        \|   Y  \  ___/|  |_|  |_|   |  \  \  \__\  ___/ 
/_______  /|___|  /\___  >____/____/___|  /__|\___  >___  >
        \/      \/     \/               \/        \/    \/ 
EOF

IFS= read -r -d '' HELP << 'EOF'
shellnice - makes your shell nice!
this will install zsh, oh-my-zsh, neovim and fastfetch.
usage: Shellnice.sh [flags] 
	flags:
		-r	reboots the machine at the end of everything
		-e	installs extended Toolset
		-h	display this text
EOF
REBOOT=false
EXTENDED=false




main() {
	## handle cli flags
	while getopts "reh" opt; do
		case $opt in
			r)	REBOOT=true;;
			e)	EXTENDED=true;;
			h)	echo "$HELP";;
		esac
	done

	## run the components:
	install_basic_toolset
	if [ "$EXTENDED" == true ]; then
		install_extended toolset
	fi
	if [ "$REBOOT" == true ]; then
		reboot_routine
	else
		echo "$WELCOME"
		echo 'all tools installed. use -r to reboot'
	fi
}



## the components

install_basic_toolset() {
	echo 'installing basic packages ...'

	## apt packages
	while read -r target; do
		echo "installing: $target"
		apt install -y "$target"
	done <<EOF
git
curl
zsh
fastfetch
neovim
EOF



	## all commands to be executed normally
	while read -r command; do
		eval "$command"
	done <<EOF
sh -c '\$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)'
apt -y upgrade
EOF
}


install_extended_toolset() {
	echo 'installing extended packages...'

	## all apt installs
	while read -r target; do
		echo "installing: $target"
		apt install -y "$target"
	done <<EOF
tmux
htop
iftop
EOF

	## all commands to be executed normally
	while read -r command; do
		eval "$command"
	done <<EOF
apt -y upgrade
EOF
}


reboot_routine() {
while read -r task; do
	shell_rc="$HOME/.zshrc"
done <<EOF >> "shell_rc" 
echo "$WELCOME"
fastfetch
EOF
reboot
}


#############################################################
main "$@"
